owner: BotSauce # GitHub username
repo: status # GitHub repository name

sites: # List of endpoints to track
  - name: BotSauce
    url: $SECRET_SITE
assignees: # Users to assign downtime issues (optional)
  - montelion
status-website:
  baseUrl: /status # where "repo" is your repository name
  name: BotSauce Status
  # logoUrl: https://example.com/image.jpg
  introMessage: "BotSauce"
  introMessage: "Here you can check the status of **BotSauce**, the bot for the official Vsauce3 Discord server"
  navbar:
    - title: Status
      href: /
    - title: Commands
      href: https://botsauce.github.io
    - title: GitHub
      href: https://github.com/BotSauce/BotSauce
    - title: Changelog
      href: https://botsauce.github.io/changelog.html

notifications:
  - type: discord
