owner: BotSauce # GitHub username
repo: status # GitHub repository name

sites: # List of endpoints to track
  - name: BotSauce
    url: $SECRET_SITE
assignees: # Users to assign downtime issues (optional)
  - montelion
status-website:
  baseUrl: /status # where "repo" is your repository name
  name: BotSauce Status
