owner: BotSauce # GitHub username
repo: status # GitHub repository name

sites: # List of endpoints to track
  - name: BotSauce
    url: $SECRET_SITE
  - name: Discord API (Messages endpoint)
    url: https://discord.com/api/channels/563066002724880404 #Checks if it can access the #general chat in the Vsauce3 server via the API endpoint
    expectedStatusCodes:
    - 401
assignees: # Users to assign downtime issues (optional)
  - montelion
status-website:
  baseUrl: /status # where "repo" is your repository name
  name: BotSauce Status
  logoUrl: https://raw.githubusercontent.com/BotSauce/botsauce.github.io/master/assets/images/botsauce_circle.png
  introTitle: "BotSauce"
  introMessage: "Here you can check the status of **BotSauce**, the bot for the official Vsauce3 Discord server"
  navbar:
    - title: Commands
      href: https://botsauce.github.io
    - title: GitHub
      href: https://github.com/BotSauce/BotSauce
    - title: Changelog
      href: https://botsauce.github.io/changelog.html
    - title: Vsauce3 Discord Server
      href: https://discord.com/invite/d5mHhPe

notifications:
  - type: discord
